export const Formulario_Becario = {
  tipo_de_documento: {
    name: "tipo_de_documento",
    type: "text",
    title: "Tipo Doc",
    placeholder: "Seleccione un tipo de documento",
    tooltip: "Seleccione un tipo de documento",
    component: "select",
    required: true,
    options: [],
  },
  numero_documento: {
    name: "numero_documento",
    type: "text",
    title: "Documento",
    placeholder: "Nro documento",
    tooltip: "Numero de documento",
    maxLength: 8,
    component: "input",
    required: true,
  },
  apellidos: {
    name: "apellidos",
    type: "text",
    title: "Apellidos",
    placeholder: "Apellidos",
    tooltip: "Apellidos",
    maxLength: 100,
    component: "input",
    required: true,
  },
  fecha_nacimiento: {
    name: "fecha_nacimiento",
    type: "date",
    title: "Fecha de Nacimiento",
    placeholder: "",
    tooltip: "Fecha de Nacimiento",
    component: "input",
    required: true,
  },
  nacionalidad: {
    name: "nacionalidad",
    type: "text",
    title: "Nacionalidad",
    placeholder: "Seleccione",
    tooltip: "Ingrese nacionalidad",
    component: "combo",
    required: true,
    options: [],
  },
  municipio: {
    name: "municipio",
    type: "text",
    title: "Municipio",
    placeholder: "Seleccione",
    tooltip: "Ingrese el municipio",
    component: "combo",
    required: true,
    options: [],
  },
  calle: {
    name: "calle",
    type: "text",
    title: "Calle",
    placeholder: "Calle",
    tooltip: "Calle Principal",
    maxLength: 50,
    component: "input",
    required: true,
  },
  numero: {
    name: "numero",
    type: "text",
    title: "Nro",
    placeholder: "Nro",
    tooltip: "Número",
    maxLength: 20,
    component: "input",
    required: true,
  },
  cuil: {
    name: "cuil",
    type: "text",
    title: "CUIL",
    placeholder: "",
    tooltip: "",
    component: "input",
    required: true,
  },
  nombres: {
    name: "nombres",
    type: "text",
    title: "Nombres",
    placeholder: "Nombres",
    tooltip: "Nombres",
    maxLength: 100,
    component: "input",
    required: true,
  },
  sexo: {
    name: "sexo",
    type: "text",
    title: "Sexo",
    tooltip: "Seleccione el sexo",
    component: "select",
    required: true,
    options: [],
  },
  correo_electronico: {
    name: "correo_electronico",
    type: "email",
    title: "E-Mail",
    placeholder: "ejemplo@mdc.gba.gov.ar",
    tooltip: "E-Mail",
    maxLength: 100,
    component: "input",
    required: true,
  },
  localidad: {
    name: "localidad",
    type: "text",
    title: "Localidad",
    placeholder: "Seleccione",
    tooltip: "Ingrese la localidad",
    component: "combo",
    required: true,
    options: [],
  },
  entre1: {
    name: "entre1",
    type: "text",
    title: "Entre",
    placeholder: "Calle",
    tooltip: "Calle entre 1",
    maxLength: 50,
    component: "input",
    required: true,
  },
  entre2: {
    name: "entre2",
    type: "text",
    title: "Entre (2)",
    placeholder: "Calle",
    tooltip: "Calle entre 2",
    maxLength: 50,
    component: "input",
    required: true,
  },
  fecha_desde: {
    name: "fecha_desde",
    type: "date",
    title: "Fecha de Alta",
    placeholder: "",
    tooltip: "Fecha de Alta",
    component: "input",
    required: true,
  },
  cbu: {
    name: "cbu",
    type: "text",
    title: "CBU",
    placeholder: "CBU",
    tooltip: "CBU",
    maxLength: 22,
    component: "input",
    required: true,
  },
  id_categoria: {
    name: "id_categoria",
    type: "text",
    title: "Categoría",
    tooltip: "Categoría",
    component: "select",
    required: true,
    options: [],
  },
  resolucion_alta: {
    name: "resolucion_alta",
    type: "text",
    title: "Resolución Alta",
    placeholder: "Resolución Alta",
    tooltip: "Resolución Alta",
    maxLength: 50,
    component: "input",
    required: true,
  },
  fecha_hasta: {
    name: "fecha_hasta",
    type: "date",
    title: "Fecha de Baja",
    placeholder: "",
    tooltip: "Fecha de Baja",
    component: "input",
    required: true,
  },
  resolucion_baja: {
    name: "resolucion_baja",
    type: "text",
    title: "Resolución Baja",
    placeholder: "Resolución Baja",
    tooltip: "Resolución Baja",
    maxLength: 50,
    component: "input",
    required: true,
  },
  observacion_baja: {
    name: "observacion_baja",
    type: "text",
    title: "Observación Baja",
    placeholder: "Observación Baja",
    tooltip: "Observación Baja",
    maxLength: 100,
    component: "input",
    required: true,
  },
};
export const Formulario_Empresa = {
  nombre_empresa: {
    name: "nombre_empresa",
    type: "text",
    title: "Nombre de la Empresa",
    placeholder: "Ingrese el nombre",
    tooltip: "Nombre legal de la empresa",
    maxLength: 150,
    component: "input",
    required: true,
  },
  cuit: {
    name: "cuit",
    type: "text",
    title: "CUIT",
    placeholder: "XX-XXXXXXXX-X",
    tooltip: "CUIT de la empresa",
    maxLength: 13,
    component: "input",
    required: true,
  },
  razon_social: {
    name: "razon_social",
    type: "text",
    title: "Razón Social",
    placeholder: "Razón social completa",
    tooltip: "Razón social registrada",
    maxLength: 150,
    component: "input",
    required: true,
  },
  tipo_empresa: {
    name: "tipo_empresa",
    type: "text",
    title: "Tipo de Empresa",
    placeholder: "Seleccione un tipo",
    tooltip: "Ej: SRL, SA, etc.",
    component: "select",
    required: true,
  },
  fecha_constitucion: {
    name: "fecha_constitucion",
    type: "date",
    title: "Fecha de Constitución",
    tooltip: "Fecha en que se constituyó legalmente",
    component: "input",
    required: true,
  },
  telefono: {
    name: "telefono",
    type: "text",
    title: "Teléfono",
    placeholder: "011-XXXX-XXXX",
    tooltip: "Teléfono de contacto",
    maxLength: 20,
    component: "input",
    required: true,
  },
  correo_empresa: {
    name: "correo_empresa",
    type: "email",
    title: "Correo Electrónico",
    placeholder: "empresa@ejemplo.com",
    tooltip: "Correo electrónico de contacto",
    maxLength: 100,
    component: "input",
    required: true,
  },
  direccion_fiscal: {
    name: "direccion_fiscal",
    type: "text",
    title: "Dirección Fiscal",
    placeholder: "Calle, número, ciudad",
    tooltip: "Dirección registrada legalmente",
    maxLength: 200,
    component: "input",
    required: true,
  },
  actividad_principal: {
    name: "actividad_principal",
    type: "text",
    title: "Actividad Principal",
    placeholder: "Ingrese actividad",
    tooltip: "Rubro principal de la empresa",
    maxLength: 100,
    component: "input",
    required: true,
  },
  cantidad_empleados: {
    name: "cantidad_empleados",
    type: "text",
    title: "Cantidad de Empleados",
    placeholder: "Ej: 50",
    tooltip: "Cantidad actual de empleados",
    component: "input",
    required: true,
  },
  sitio_web: {
    name: "sitio_web",
    type: "text",
    title: "Sitio Web",
    placeholder: "https://ejemplo.com",
    tooltip: "Página web de la empresa (opcional)",
    maxLength: 100,
    component: "input",
    required: false,
  },
};
